import { useState } from 'react'
import { Zap, Download, RefreshCw, Terminal } from 'lucide-react'
import CodeBlock from '@/components/features/CodeBlock'
import StatusBadge from '@/components/features/StatusBadge'

type ScriptType = 'powershell_mutex' | 'batch_mutex' | 'process_explorer_guide' | 'startup_script'

interface ScriptConfig {
  type: ScriptType
  autoClose: boolean
  showNotification: boolean
  mutexCount: number
}

const SCRIPT_INFO: Record<ScriptType, { title: string; desc: string; difficulty: 'Beginner' | 'Intermediate' | 'Advanced' }> = {
  powershell_mutex: { title: 'PowerShell Mutex Holder', desc: 'Claims ROBLOX_singletonEvent before Roblox. Best all-round method.', difficulty: 'Beginner' },
  batch_mutex: { title: 'Batch File Launcher', desc: 'Simple .bat file that calls PowerShell mutex + opens Roblox URL.', difficulty: 'Beginner' },
  process_explorer_guide: { title: 'Process Explorer AutoHotkey', desc: 'AHK macro to automate handle-close in Process Explorer.', difficulty: 'Intermediate' },
  startup_script: { title: 'Windows Startup Script', desc: 'Runs mutex holder automatically on system startup via Task Scheduler.', difficulty: 'Intermediate' },
}

const AHK_SCRIPT = [
  '; ============================================================',
  '; MultiRBX -- AutoHotkey v1 Script',
  '; Automates the Process Explorer handle-close method',
  '; Generated by MultiRBX Hub -- multirblx.onspace.app',
  '; ============================================================',
  '; REQUIREMENTS: AutoHotkey v1.x + Process Explorer running as Admin',
  '; HOTKEY: Win + F2 = Close singleton handle for front Roblox instance',
  '; ============================================================',
  '',
  '#NoEnv',
  '#SingleInstance Force',
  'SetWorkingDir %A_ScriptDir%',
  '',
  '; ---- Configuration ----',
  'ProcExpPath := "C:\\SysinternalsSuite\\procexp64.exe"',
  'MutexTarget := "ROBLOX_singletonEvent"',
  '',
  '; ---- Hotkey: Win+F2 = release singleton for active Roblox ----',
  '#F2::',
  '    ToolTip, MultiRBX: Searching for Roblox singleton handle...',
  '    ',
  '    ; Check if Process Explorer is running',
  '    IfWinNotExist, Process Explorer',
  '    {',
  '        MsgBox, 16, MultiRBX Error, Process Explorer is not running!',
  '        ToolTip',
  '        return',
  '    }',
  '    ',
  '    ; Find Roblox process',
  '    Process, Exist, RobloxPlayerBeta.exe',
  '    if (!ErrorLevel) {',
  '        MsgBox, 16, MultiRBX, No Roblox instance found running.',
  '        ToolTip',
  '        return',
  '    }',
  '    RobloxPID := ErrorLevel',
  '    ',
  '    ToolTip, MultiRBX: Found Roblox PID %RobloxPID%. Closing singleton handle...',
  '    Sleep, 500',
  '    ',
  '    ; Switch to Process Explorer and use Find Handle',
  '    WinActivate, Process Explorer',
  '    Sleep, 300',
  '    ',
  '    ; Open Find Handle dialog (Ctrl+F in ProcExp)',
  '    Send, ^f',
  '    Sleep, 400',
  '    Send, %MutexTarget%',
  '    Sleep, 300',
  '    Send, {Enter}',
  '    Sleep, 800',
  '    ',
  '    ToolTip, MultiRBX: Handle search done. Right-click result to Close Handle.',
  '    Sleep, 2000',
  '    ToolTip',
  'return',
  '',
  '; ---- Hotkey: Win+F3 = Show help ----',
  '#F3::',
  '    MsgBox, 64, MultiRBX Help,',
  '    (',
  'MultiRBX AHK Script - Hotkeys:',
  '',
  'Win + F2  =  Find and target ROBLOX_singletonEvent handle',
  '             (You still need to right-click > Close Handle in ProcExp)',
  '',
  'Win + F3  =  Show this help',
  '',
  'Steps:',
  '1. Run Process Explorer as Admin (procexp64.exe)',
  '2. Enable View > Lower Pane > Handles',
  '3. Launch Roblox + join a game',
  '4. Press Win+F2 -- ProcExp will search for the handle',
  '5. Right-click ROBLOX_singletonEvent > Close Handle',
  '6. Log out on roblox.com (keep game window open)',
  '7. Log in with Account 2 and join another game',
  '    )',
  'return',
].join('\n')

function generateScript(config: ScriptConfig): string {
  switch (config.type) {
    case 'powershell_mutex':
      return `# ============================================================
# MultiRBX -- PowerShell Mutex Pre-Claim Script
# Generated by MultiRBX Hub -- multirblx.onspace.app
# ============================================================
# INSTRUCTIONS:
#   1. Run this script as Administrator
#   2. Keep this window open while playing
#   3. Launch Roblox normally (as many instances as you want)
#   4. Press CTRL+C to stop when done
# ============================================================

Add-Type -TypeDefinition @"
using System;
using System.Threading;
using System.Runtime.InteropServices;

public class MultiRBXMutex {
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern IntPtr CreateMutex(IntPtr lpMutexAttributes, bool bInitialOwner, string lpName);
    
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool ReleaseMutex(IntPtr hMutex);

    public static IntPtr[] handles = new IntPtr[${config.mutexCount}];

    public static void HoldAll() {
        string[] mutexNames = { 
            "ROBLOX_singletonEvent"${config.mutexCount > 1 ? ',\n            "Global\\\\ROBLOX_singletonEvent"' : ''}
        };
        for (int i = 0; i < mutexNames.Length && i < ${config.mutexCount}; i++) {
            handles[i] = CreateMutex(IntPtr.Zero, true, mutexNames[i]);
            if (handles[i] != IntPtr.Zero) {
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("[OK] Mutex claimed: " + mutexNames[i]);
                Console.ResetColor();
            }
        }
    }
}
"@

Clear-Host
Write-Host "============================================================" -ForegroundColor DarkCyan
Write-Host "  MultiRBX -- Roblox Multi-Instance Mutex Holder" -ForegroundColor Cyan
Write-Host "  Generated by MultiRBX Hub" -ForegroundColor DarkGray
Write-Host "============================================================" -ForegroundColor DarkCyan
Write-Host ""

# Claim mutex(es)
[MultiRBXMutex]::HoldAll()

Write-Host ""
Write-Host "[ACTIVE] Mutex is held. Roblox instances will not kill each other." -ForegroundColor Green
Write-Host "[INFO]   Launch Roblox instances now (open roblox.com, click Play)" -ForegroundColor Cyan
Write-Host "[INFO]   Keep this window open the entire time." -ForegroundColor Yellow
Write-Host "[INFO]   Press CTRL+C to release mutex and stop." -ForegroundColor DarkGray
Write-Host ""
${config.showNotification ? `# Windows notification
$notif = New-Object -ComObject WScript.Shell
$notif.Popup("MultiRBX mutex is active! Launch Roblox instances now.", 3, "MultiRBX", 64) | Out-Null
` : ''}
# Keep alive loop
$counter = 0
while ($true) {
    Start-Sleep -Seconds 5
    $counter += 5
    $mins = [math]::Floor($counter / 60)
    $secs = $counter % 60
    Write-Host -NoNewline ([char]13 + "[RUNNING] Uptime: " + $mins + "m " + $secs + "s -- Instances protected...")
}
`

    case 'batch_mutex':
      return `@echo off
:: ============================================================
:: MultiRBX -- Batch Launcher with Mutex Pre-Claim
:: Generated by MultiRBX Hub -- multirblx.onspace.app
:: ============================================================
:: Double-click this file to launch. Keep window open!
:: ============================================================

title MultiRBX Launcher
color 0A
cls

echo ============================================================
echo   MultiRBX - Roblox Multi-Instance Launcher
echo   Powered by PowerShell Mutex Method
echo ============================================================
echo.
echo [*] Claiming ROBLOX_singletonEvent mutex...
echo [*] Keep this window open while running multiple instances.
echo.

:: Run the PowerShell mutex holder inline (minimized background window)
start "MultiRBX Mutex" /min powershell.exe -WindowStyle Minimized -ExecutionPolicy Bypass -Command "Add-Type -TypeDefinition 'using System; using System.Threading; public class M { public static Mutex m; public static void H() { bool c; m = new Mutex(true, ""ROBLOX_singletonEvent"", out c); } }'; [M]::H(); while($true){Start-Sleep 30}"

timeout /t 2 /nobreak >nul

echo [OK] Mutex claimed! Now open Roblox instances below.
echo.
echo [1] Open Roblox (Account 1) - go to roblox.com and join a game
echo.
echo [2] After Account 1 is in-game, log out on the website
echo     (keep the game window open!)
echo.
echo [3] Log in with Account 2 and join another game.
echo.
echo [4] Repeat for each additional account.
echo.
echo Press any key to open Roblox website...
pause >nul
start "" "https://www.roblox.com/"

echo.
echo [MultiRBX] Browser opened. Follow the steps above.
echo [MultiRBX] The mutex process runs in a minimized window.
echo [MultiRBX] Close this window when done playing.
echo.
pause
`

    case 'process_explorer_guide':
      return AHK_SCRIPT

    case 'startup_script':
      return `# ============================================================
# MultiRBX -- Windows Task Scheduler Auto-Startup Script
# Generated by MultiRBX Hub -- multirblx.onspace.app
# ============================================================
# Run this script ONCE as Administrator to set up auto-start.
# After setup, the mutex holder starts automatically on login.
# To remove: run with -Remove switch
# ============================================================

param(
    [switch]$Remove
)

$TaskName = "MultiRBX-MutexHolder"
$ScriptPath = "$env:APPDATA\\MultiRBX\\mutex_holder.ps1"

if ($Remove) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "[OK] MultiRBX startup task removed." -ForegroundColor Yellow
    exit
}

# Create the directory
New-Item -ItemType Directory -Path "$env:APPDATA\\MultiRBX" -Force | Out-Null

# Write the persistent mutex script to AppData
$mutexScript = 'Add-Type -TypeDefinition @"
using System;
using System.Threading;
public class MultiRBXMutex {
    public static Mutex m;
    public static void Hold() {
        bool created;
        m = new Mutex(true, ""ROBLOX_singletonEvent"", out created);
    }
}
"@
[MultiRBXMutex]::Hold()
while ($true) { Start-Sleep -Seconds 30 }'

Set-Content -Path $ScriptPath -Value $mutexScript -Encoding UTF8

# Create Task Scheduler entry
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File ""$ScriptPath"""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 0) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  MultiRBX Startup Task Installed!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "[OK] Task: $TaskName" -ForegroundColor Green
Write-Host "[OK] Script: $ScriptPath" -ForegroundColor Green
Write-Host "[OK] Trigger: At Login (runs hidden in background)" -ForegroundColor Green
Write-Host ""
Write-Host "[INFO] The mutex holder will now start automatically on every login." -ForegroundColor Cyan
Write-Host "[INFO] To remove: run this script with the -Remove flag" -ForegroundColor DarkGray
Write-Host ""

# Start it immediately too
Start-ScheduledTask -TaskName $TaskName
Write-Host "[ACTIVE] Mutex holder is now running!" -ForegroundColor Green
`

    default:
      return '# Unknown script type'
  }
}

export default function ScriptGeneratorPage() {
  const [config, setConfig] = useState<ScriptConfig>({
    type: 'powershell_mutex',
    autoClose: false,
    showNotification: true,
    mutexCount: 1,
  })

  const script = generateScript(config)
  const info = SCRIPT_INFO[config.type]
  const ext = config.type === 'batch_mutex' ? '.bat' : config.type === 'process_explorer_guide' ? '.ahk' : '.ps1'
  const filename = `multirblx_${config.type}${ext}`

  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen pt-24 pb-20">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-10">
          <div className="font-mono text-xs text-muted-foreground uppercase tracking-widest mb-2">Tool</div>
          <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-3">
            Script <span className="gradient-text">Generator</span>
          </h1>
          <p className="text-muted-foreground text-base leading-relaxed max-w-2xl">
            Configure and generate ready-to-run scripts for bypassing the Roblox singleton mutex.
            Copy or download — no editing required.
          </p>
        </div>

        <div className="grid lg:grid-cols-5 gap-6">
          {/* Config panel */}
          <div className="lg:col-span-2 space-y-5">
            <div className="card-dark rounded-xl p-5">
              <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
                Script Type
              </h3>
              <div className="space-y-2">
                {(Object.entries(SCRIPT_INFO) as [ScriptType, typeof SCRIPT_INFO[ScriptType]][]).map(([key, val]) => (
                  <button
                    key={key}
                    onClick={() => setConfig(c => ({ ...c, type: key }))}
                    className={`w-full text-left p-3 rounded-lg border transition-all ${
                      config.type === key
                        ? 'border-[hsl(180,100%,50%)/0.4] bg-[hsl(180,100%,50%)/0.07]'
                        : 'border-border hover:border-[hsl(180,100%,50%)/0.2] hover:bg-secondary'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <span className={`font-semibold text-sm ${config.type === key ? 'text-[hsl(180,100%,50%)]' : 'text-foreground'}`}>
                        {val.title}
                      </span>
                      <StatusBadge
                        label={val.difficulty}
                        variant={val.difficulty === 'Beginner' ? 'beginner' : 'intermediate'}
                      />
                    </div>
                    <p className="text-xs text-muted-foreground leading-snug">{val.desc}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Options */}
            {config.type === 'powershell_mutex' && (
              <div className="card-dark rounded-xl p-5 space-y-4">
                <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider">Options</h3>

                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-sm font-medium text-foreground">Windows Notification</div>
                    <div className="text-xs text-muted-foreground">Show popup when mutex is active</div>
                  </div>
                  <div
                    onClick={() => setConfig(c => ({ ...c, showNotification: !c.showNotification }))}
                    className={`w-10 h-5 rounded-full transition-all relative cursor-pointer ${config.showNotification ? 'bg-[hsl(180,100%,45%)]' : 'bg-secondary border border-border'}`}
                  >
                    <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all ${config.showNotification ? 'left-5' : 'left-0.5'}`} />
                  </div>
                </div>

                <div>
                  <div className="text-sm font-medium text-foreground mb-2">Mutex Variants: {config.mutexCount}</div>
                  <input
                    type="range"
                    min={1}
                    max={2}
                    value={config.mutexCount}
                    onChange={e => setConfig(c => ({ ...c, mutexCount: Number(e.target.value) }))}
                    className="w-full accent-[hsl(180,100%,50%)]"
                  />
                  <div className="flex justify-between text-xs text-muted-foreground font-mono mt-1">
                    <span>1 (standard)</span>
                    <span>2 (+ global)</span>
                  </div>
                </div>
              </div>
            )}

            {/* Download */}
            <div className="flex gap-3">
              <button
                onClick={handleDownload}
                className="btn-primary flex-1 px-4 py-3 rounded-lg flex items-center justify-center gap-2 text-sm font-semibold"
              >
                <Download className="w-4 h-4" />
                Download {ext}
              </button>
              <button
                onClick={() => setConfig(c => ({ ...c }))}
                className="px-3 py-3 rounded-lg border border-border text-muted-foreground hover:text-foreground hover:border-[hsl(180,100%,50%)/0.3] transition-all"
                title="Regenerate"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            </div>

            {/* Usage tip */}
            <div className="p-4 rounded-lg bg-[hsl(180,100%,50%)/0.05] border border-[hsl(180,100%,50%)/0.15] text-xs font-mono text-muted-foreground space-y-1">
              <div className="text-[hsl(180,100%,50%)] font-semibold mb-2 flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5" />
                Run Instructions
              </div>
              {config.type === 'powershell_mutex' && (
                <>
                  <p>1. Right-click the .ps1 file</p>
                  <p>2. Select "Run with PowerShell"</p>
                  <p>3. Accept "Run as Administrator"</p>
                  <p>4. Keep the window open</p>
                </>
              )}
              {config.type === 'batch_mutex' && (
                <>
                  <p>1. Right-click the .bat file</p>
                  <p>2. Select "Run as Administrator"</p>
                  <p>3. Follow on-screen instructions</p>
                </>
              )}
              {config.type === 'process_explorer_guide' && (
                <>
                  <p>1. Install AutoHotkey v1.x</p>
                  <p>2. Double-click the .ahk file</p>
                  <p>3. Run Process Explorer as Admin</p>
                  <p>4. Press Win+F2 after Roblox loads</p>
                </>
              )}
              {config.type === 'startup_script' && (
                <>
                  <p>1. Right-click the .ps1 file</p>
                  <p>2. Select "Run as Administrator"</p>
                  <p>3. Run ONCE to install startup task</p>
                  <p>4. Mutex auto-starts on every login</p>
                </>
              )}
            </div>
          </div>

          {/* Code preview */}
          <div className="lg:col-span-3">
            <div className="sticky top-24">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-[hsl(180,100%,50%)]" />
                  <span className="font-mono text-sm font-semibold text-foreground">{info.title}</span>
                </div>
                <span className="font-mono text-xs text-muted-foreground">{filename}</span>
              </div>
              <CodeBlock
                code={script}
                label={filename}
                language={ext.replace('.', '')}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
