import { useState } from 'react'
import { Zap, Download, RefreshCw, Terminal, AlertTriangle, Shield } from 'lucide-react'
import CodeBlock from '@/components/features/CodeBlock'
import StatusBadge from '@/components/features/StatusBadge'
import type { ScriptType } from '@/types'

interface ScriptConfig {
  type: ScriptType
  showNotification: boolean
  mutexCount: number
  handlePath: string
  altUser: string
}

const SCRIPT_INFO: Record<ScriptType, {
  title: string
  desc: string
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  ext: string
  safety: 'Safe' | 'Caution'
}> = {
  powershell_mutex: {
    title: 'PowerShell Mutex Holder',
    desc: 'Claims ROBLOX_singletonEvent before Roblox launches. Best all-round method.',
    difficulty: 'Beginner',
    ext: '.ps1',
    safety: 'Safe',
  },
  handle_auto_close: {
    title: 'Handle.exe Auto-Close Loop',
    desc: 'Uses Microsoft Handle.exe to auto-close the singleton handle as soon as Roblox creates it.',
    difficulty: 'Intermediate',
    ext: '.ps1',
    safety: 'Safe',
  },
  batch_launcher: {
    title: 'Batch Launcher (.bat)',
    desc: 'Double-click .bat launcher that runs the mutex in background + opens Roblox.',
    difficulty: 'Beginner',
    ext: '.bat',
    safety: 'Safe',
  },
  startup_task: {
    title: 'Windows Startup Task',
    desc: 'Installs a Task Scheduler entry so the mutex auto-starts on every Windows login.',
    difficulty: 'Intermediate',
    ext: '.ps1',
    safety: 'Safe',
  },
  ahk_process_explorer: {
    title: 'AutoHotkey — Process Explorer Helper',
    desc: 'AHK macro that automates finding the singleton handle in Process Explorer.',
    difficulty: 'Intermediate',
    ext: '.ahk',
    safety: 'Safe',
  },
  windows_sandbox_config: {
    title: 'Windows Sandbox Config (.wsb)',
    desc: 'Pre-configured sandbox that opens Roblox in an isolated container automatically.',
    difficulty: 'Intermediate',
    ext: '.wsb',
    safety: 'Safe',
  },
  runas_launcher: {
    title: 'RunAs User Launcher (.bat)',
    desc: 'Launches Roblox as a different Windows user account for mutex namespace isolation.',
    difficulty: 'Advanced',
    ext: '.bat',
    safety: 'Safe',
  },
}

const AHK_LINES = [
  '; ============================================================',
  '; MultiRBX -- AutoHotkey v1 Script',
  '; Automates the Process Explorer handle-close method',
  '; REQUIREMENTS: AutoHotkey v1.x + Process Explorer running as Admin',
  '; HOTKEY: Win + F2 = Close singleton handle in Process Explorer',
  '; ============================================================',
  '',
  '#NoEnv',
  '#SingleInstance Force',
  'SetWorkingDir %A_ScriptDir%',
  '',
  'ProcExpPath := "C:\\SysinternalsSuite\\procexp64.exe"',
  'MutexTarget := "ROBLOX_singletonEvent"',
  '',
  '; Win+F2 = Find and close the singleton handle',
  '#F2::',
  '    ToolTip, MultiRBX: Searching for ROBLOX_singletonEvent...',
  '    IfWinNotExist, ahk_exe procexp64.exe',
  '    {',
  '        MsgBox, 16, MultiRBX Error, Process Explorer is not running!',
  '        ToolTip',
  '        return',
  '    }',
  '    Process, Exist, RobloxPlayerBeta.exe',
  '    if (!ErrorLevel) {',
  '        MsgBox, 16, MultiRBX, No Roblox instance found.',
  '        ToolTip',
  '        return',
  '    }',
  '    RobloxPID := ErrorLevel',
  '    ToolTip, MultiRBX: Found Roblox PID %RobloxPID%.',
  '    Sleep, 400',
  '    WinActivate, ahk_exe procexp64.exe',
  '    Sleep, 300',
  '    Send, ^f',
  '    Sleep, 400',
  '    Send, %MutexTarget%',
  '    Sleep, 300',
  '    Send, {Enter}',
  '    Sleep, 800',
  '    ToolTip, MultiRBX: Search done. Right-click ROBLOX_singletonEvent > Close Handle.',
  '    Sleep, 3000',
  '    ToolTip',
  'return',
  '',
  '; Win+F3 = Show help',
  '#F3::',
  '    MsgBox, 64, MultiRBX Help, MultiRBX AHK Hotkeys:`n`nWin+F2 = Search for ROBLOX_singletonEvent in ProcExp`nWin+F3 = This help`n`nSteps:`n1. Run Process Explorer as Admin`n2. Enable View > Lower Pane > Handles`n3. Launch Roblox + join a game`n4. Press Win+F2 to search for the handle`n5. Right-click > Close Handle`n6. Log out on roblox.com, log in with Account 2',
  'return',
]
const AHK_SCRIPT = AHK_LINES.join('\n')

function generateScript(config: ScriptConfig): string {
  switch (config.type) {

    case 'powershell_mutex':
      return `# ============================================================
# MultiRBX -- PowerShell Mutex Pre-Claim Script
# Generated by MultiRBX Hub
# ============================================================
# HOW TO USE:
#   1. Right-click this file -> "Run with PowerShell"
#   2. When prompted, click "Open" or allow execution
#   3. Keep the PowerShell window open during gaming
#   4. Launch Roblox instances freely
#   5. Press CTRL+C when done to release the mutex
# ============================================================

# Allow script execution for this session
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

Add-Type -TypeDefinition @"
using System;
using System.Threading;
using System.Runtime.InteropServices;

public class MultiRBXMutex {
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern IntPtr CreateMutex(
        IntPtr lpMutexAttributes,
        bool bInitialOwner,
        string lpName
    );

    public static IntPtr handle1 = IntPtr.Zero;
    public static IntPtr handle2 = IntPtr.Zero;

    public static void HoldAll() {
        handle1 = CreateMutex(IntPtr.Zero, true, "ROBLOX_singletonEvent");
        if (handle1 != IntPtr.Zero) {
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine("[OK] Claimed: ROBLOX_singletonEvent");
            Console.ResetColor();
        }
${config.mutexCount > 1 ? `        handle2 = CreateMutex(IntPtr.Zero, true, "Global\\\\ROBLOX_singletonEvent");
        if (handle2 != IntPtr.Zero) {
            Console.ForegroundColor = ConsoleColor.Cyan;
            Console.WriteLine("[OK] Claimed: Global\\\\ROBLOX_singletonEvent");
            Console.ResetColor();
        }` : '        // Single mutex variant selected'}
    }
}
"@

Clear-Host
Write-Host "======================================================" -ForegroundColor DarkCyan
Write-Host "  MultiRBX Mutex Holder -- Active" -ForegroundColor Cyan
Write-Host "  Generated by MultiRBX Hub" -ForegroundColor DarkGray
Write-Host "======================================================" -ForegroundColor DarkCyan
Write-Host ""

[MultiRBXMutex]::HoldAll()

Write-Host ""
Write-Host "[READY]  Launch Roblox instances NOW" -ForegroundColor Green
Write-Host "[INFO]   Keep this window open the entire session" -ForegroundColor Yellow
Write-Host "[INFO]   Press CTRL+C when done" -ForegroundColor DarkGray
Write-Host ""
${config.showNotification ? `# Pop-up notification
Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.MessageBox]::Show("MultiRBX mutex is active!`nLaunch Roblox instances now.", "MultiRBX", "OK", "Information") | Out-Null
` : ''}
$elapsed = 0
while ($true) {
    Start-Sleep -Seconds 5
    $elapsed += 5
    $m = [math]::Floor($elapsed / 60)
    $s = $elapsed % 60
    Write-Host -NoNewline ("`r[RUNNING] Uptime: $($m)m $($s)s -- Mutex active, instances protected... ")
}
`

    case 'handle_auto_close':
      return `# ============================================================
# MultiRBX -- Handle.exe Auto-Close Loop Script
# Generated by MultiRBX Hub
# ============================================================
# REQUIREMENTS: Microsoft Handle.exe (Sysinternals)
# Download: https://download.sysinternals.com/files/Handle.zip
# ============================================================
# HOW TO USE:
#   1. Download Handle.zip from Microsoft (link above)
#   2. Extract handle.exe and update $HandleExe path below
#   3. Run this script as Administrator
#   4. Launch Roblox instances freely
# ============================================================

param()
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

# ---- EDIT THIS PATH TO MATCH WHERE YOU EXTRACTED handle.exe ----
$HandleExe = "${config.handlePath || 'C:\\Tools\\Handle\\handle.exe'}"
# ----------------------------------------------------------------

if (-not (Test-Path $HandleExe)) {
    Write-Host "[ERROR] handle.exe not found at: $HandleExe" -ForegroundColor Red
    Write-Host "[INFO]  Download from: https://download.sysinternals.com/files/Handle.zip" -ForegroundColor Cyan
    Write-Host "[INFO]  Then update the HandleExe path in this script." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

# Accept EULA silently
& $HandleExe -accepteula 2>&1 | Out-Null

# Also accept via registry (prevents EULA popup in future runs)
reg add "HKCU\\Software\\Sysinternals\\Handle" /v EulaAccepted /t REG_DWORD /d 1 /f | Out-Null

Clear-Host
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  MultiRBX -- Sysinternals Handle.exe Singleton Watcher" -ForegroundColor Green
Write-Host "  Generated by MultiRBX Hub" -ForegroundColor DarkGray
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "[ACTIVE] Watching for ROBLOX_singletonEvent..." -ForegroundColor Green
Write-Host "[INFO]   Launch Roblox instances freely now." -ForegroundColor Yellow
Write-Host "[INFO]   Press CTRL+C to stop." -ForegroundColor DarkGray
Write-Host ""

$logFile = Join-Path $PSScriptRoot "multirblx_log.txt"
$closedCount = 0

while ($true) {
    try {
        $output = & $HandleExe -p RobloxPlayerBeta.exe -accepteula 2>&1
        foreach ($line in $output) {
            if ($line -match "ROBLOX_singletonEvent") {
                if ($line -match "([0-9A-Fa-f]+):") {
                    $handleId = $Matches[1]
                    $ts = Get-Date -Format "HH:mm:ss"
                    Write-Host "[$ts] [FOUND] Handle $handleId -- closing..." -ForegroundColor Yellow
                    & $HandleExe -p RobloxPlayerBeta.exe -c $handleId -y -accepteula 2>&1 | Out-Null
                    $closedCount++
                    Write-Host "[$ts] [CLOSED] ROBLOX_singletonEvent (#$closedCount total)" -ForegroundColor Green
                    $logEntry = "[$ts] Closed ROBLOX_singletonEvent handle: $handleId (total: $closedCount)"
                    Add-Content -Path $logFile -Value $logEntry -ErrorAction SilentlyContinue
                }
            }
        }
    } catch {
        # Roblox not running yet -- keep polling
    }
    Start-Sleep -Milliseconds 500
}
`

    case 'batch_launcher':
      return `@echo off
:: ============================================================
:: MultiRBX -- Batch File Launcher
:: Generated by MultiRBX Hub
:: ============================================================
:: Double-click this .bat file to start.
:: A minimized mutex holder runs in the background.
:: Keep this window open while gaming.
:: ============================================================

title MultiRBX Launcher
color 0A
cls

echo ============================================================
echo   MultiRBX - Roblox Multi-Instance Launcher
echo ============================================================
echo.
echo [*] Starting mutex holder in background...

:: Launch the PowerShell mutex holder minimized
start "MultiRBX Mutex" /min powershell.exe -WindowStyle Minimized -ExecutionPolicy Bypass -NoProfile -Command ^
  "Add-Type -TypeDefinition 'using System; using System.Threading; using System.Runtime.InteropServices; public class M { [DllImport(\"kernel32.dll\")] public static extern IntPtr CreateMutex(IntPtr a, bool b, string c); public static void Run() { CreateMutex(IntPtr.Zero, true, \"ROBLOX_singletonEvent\"); CreateMutex(IntPtr.Zero, true, \"Global\\ROBLOX_singletonEvent\"); } }'; [M]::Run(); while($true){Start-Sleep 30}"

timeout /t 2 /nobreak >nul

echo [OK] Mutex holder is running in the background!
echo.
echo ============================================================
echo   LAUNCH INSTRUCTIONS
echo ============================================================
echo.
echo  STEP 1: Open roblox.com in your browser
echo          Log in as Account 1
echo          Join any game. KEEP THE GAME WINDOW OPEN.
echo.
echo  STEP 2: Go back to roblox.com
echo          Log OUT of Account 1 (keep the game window open!)
echo          Log IN as Account 2
echo          Join a game. A second instance will open.
echo.
echo  STEP 3: Repeat Step 2 for each additional account.
echo.
echo ============================================================
echo.
echo Press any key to open roblox.com...
pause >nul

start "" "https://www.roblox.com/"

echo.
echo [MultiRBX] Browser opened. Follow the steps above.
echo [MultiRBX] The mutex process runs minimized in the background.
echo [MultiRBX] Close this window when you are done gaming.
echo.
pause
`

    case 'startup_task':
      return `# ============================================================
# MultiRBX -- Windows Task Scheduler Auto-Startup Installer
# Generated by MultiRBX Hub
# ============================================================
# HOW TO USE:
#   Run this script ONCE as Administrator to install.
#   The mutex holder will then auto-start on every Windows login.
#   To uninstall: run with -Remove switch:
#     powershell -File multirblx_startup.ps1 -Remove
# ============================================================

param([switch]$Remove)

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

$TaskName   = "MultiRBX-MutexHolder"
$InstallDir = "$env:APPDATA\\MultiRBX"
$ScriptPath = "$InstallDir\\mutex_holder.ps1"

if ($Remove) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "[OK] Task '$TaskName' removed." -ForegroundColor Yellow
    Write-Host "[OK] MultiRBX will no longer auto-start." -ForegroundColor Yellow
    exit 0
}

Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  MultiRBX -- Startup Task Installer" -ForegroundColor Green
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""

# Create install directory
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

# Write the persistent mutex script to AppData\\MultiRBX
$mutexContent = @'
# MultiRBX Mutex Holder (auto-started by Task Scheduler)
Add-Type -TypeDefinition @"
using System;
using System.Threading;
using System.Runtime.InteropServices;
public class MultiRBXMutex {
    [DllImport("kernel32.dll")] public static extern IntPtr CreateMutex(IntPtr a, bool b, string c);
    public static void Hold() {
        CreateMutex(IntPtr.Zero, true, "ROBLOX_singletonEvent");
        CreateMutex(IntPtr.Zero, true, @"Global\ROBLOX_singletonEvent");
    }
}
"@
[MultiRBXMutex]::Hold()
while ($true) { Start-Sleep -Seconds 60 }
'@

Set-Content -Path $ScriptPath -Value $mutexContent -Encoding UTF8

# Register Task Scheduler task
$action    = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -NonInteractive -File `"$ScriptPath`""
$trigger   = New-ScheduledTaskTrigger -AtLogOn
$settings  = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 0) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null

Write-Host "[OK] Task installed: $TaskName" -ForegroundColor Green
Write-Host "[OK] Script saved to: $ScriptPath" -ForegroundColor Green
Write-Host "[OK] Trigger: At every login (runs hidden in background)" -ForegroundColor Green
Write-Host ""

# Start the task immediately
Start-ScheduledTask -TaskName $TaskName
Write-Host "[ACTIVE] Mutex holder is running NOW!" -ForegroundColor Green
Write-Host ""
Write-Host "[INFO] From now on, multi-instance will work automatically at login." -ForegroundColor Cyan
Write-Host "[INFO] To uninstall: run this script with -Remove" -ForegroundColor DarkGray
Write-Host ""
Read-Host "Press Enter to exit"
`

    case 'ahk_process_explorer':
      return AHK_SCRIPT

    case 'windows_sandbox_config':
      return `<!-- ============================================================
     MultiRBX -- Windows Sandbox Configuration (.wsb)
     Generated by MultiRBX Hub
     ============================================================
     REQUIREMENTS: Windows 10/11 Pro or Enterprise
     
     HOW TO ENABLE WINDOWS SANDBOX:
     1. Open PowerShell as Administrator
     2. Run: Enable-WindowsOptionalFeature -Online -FeatureName "Containers-DisposableClientVM" -All
     3. Restart your PC
     
     HOW TO USE THIS FILE:
     1. Save this file as "RobloxSandbox.wsb"
     2. Double-click it to launch the sandbox
     3. Inside the sandbox, go to roblox.com and install Roblox
     4. Log in with an alt account
     5. This is 100% isolated from your main Roblox session
     
     NOTE: Everything inside the sandbox is WIPED when you close it.
     You must re-install Roblox each time you open the sandbox.
     ============================================================ -->

<Configuration>
  <!-- Enable GPU acceleration for better Roblox performance -->
  <VGpu>Enable</VGpu>
  
  <!-- Allow internet access (required for Roblox) -->
  <Networking>Enable</Networking>
  
  <!-- Optional: Map a shared folder from your main PC into the sandbox -->
  <!-- Useful for copying files like Roblox installer into sandbox -->
  <!--
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\\Users\\YourName\\Downloads</HostFolder>
      <SandboxFolder>C:\\Sandbox\\Downloads</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  -->
  
  <!-- Auto-open Roblox website when sandbox starts -->
  <LogonCommand>
    <Command>cmd /c start https://www.roblox.com/</Command>
  </LogonCommand>
  
  <!-- Disable printer (not needed, reduces attack surface) -->
  <PrinterRedirection>Disable</PrinterRedirection>
  
  <!-- Disable audio (optional - enable if you want sound in sandbox) -->
  <!-- <AudioInput>Disable</AudioInput> -->
</Configuration>
`

    case 'runas_launcher':
      return `@echo off
:: ============================================================
:: MultiRBX -- RunAs Different Windows User Launcher
:: Generated by MultiRBX Hub
:: ============================================================
:: PREREQUISITES:
::   1. Create a secondary Windows user account first:
::      Settings > Accounts > Family & other users > Add someone
::      (or via CMD as Admin: net user RobloxAlt Password123 /add)
::
::   2. Edit the USERNAME and ROBLOX_PATH variables below
::   3. Run this .bat file (no admin rights needed for the bat itself)
::
:: HOW IT WORKS:
::   Each Windows user has a SEPARATE mutex namespace.
::   ROBLOX_singletonEvent created by User A is INVISIBLE to User B.
::   This is one of the most stable methods -- Roblox cannot patch it.
:: ============================================================

title MultiRBX - RunAs Launcher
color 0B
cls

echo ============================================================
echo   MultiRBX - Separate Windows User Launcher
echo ============================================================
echo.

:: ---- EDIT THESE VARIABLES ----
set ALT_USERNAME=${config.altUser || 'RobloxAlt1'}
set ROBLOX_PATH=%LocalAppData%\\Roblox\\Versions

:: Find the latest Roblox version folder automatically
for /f "delims=" %%i in ('dir /b /ad "%ROBLOX_PATH%\\version-*" 2^>nul') do set ROBLOX_VERSION=%%i

if "%ROBLOX_VERSION%"=="" (
    echo [ERROR] Could not find Roblox installation in:
    echo         %ROBLOX_PATH%
    echo.
    echo [FIX] Make sure Roblox is installed. Open roblox.com and join a game to install.
    pause
    exit /b 1
)

set ROBLOX_EXE=%ROBLOX_PATH%\\%ROBLOX_VERSION%\\RobloxPlayerBeta.exe
echo [INFO] Roblox found: %ROBLOX_EXE%
echo [INFO] Launching as Windows user: %ALT_USERNAME%
echo.

:: Prompt for alternate user credentials and launch Roblox
runas /user:%ALT_USERNAME% "%ROBLOX_EXE%"

if errorlevel 1 (
    echo.
    echo [ERROR] Launch failed. Possible reasons:
    echo   - Wrong username (check Settings > Accounts)
    echo   - Wrong password entered
    echo   - User account does not have Roblox in its profile
    echo.
    echo [FIX 1] Create the user via Admin CMD:
    echo         net user %ALT_USERNAME% YourPassword /add
    echo.
    echo [FIX 2] If Roblox is not installed for that user,
    echo         log in as %ALT_USERNAME% once and install Roblox.
    echo.
    pause
) else (
    echo.
    echo [OK] Roblox launched as %ALT_USERNAME%!
    echo [INFO] Log in with your alternate Roblox account in the new window.
    echo [INFO] The mutex namespace is completely separate from your main account.
    echo.
    pause
)
`

    default:
      return '# Unknown script type'
  }
}

export default function ScriptGeneratorPage() {
  const [config, setConfig] = useState<ScriptConfig>({
    type: 'powershell_mutex',
    showNotification: true,
    mutexCount: 2,
    handlePath: 'C:\\Tools\\Handle\\handle.exe',
    altUser: 'RobloxAlt1',
  })

  const script = generateScript(config)
  const info = SCRIPT_INFO[config.type]
  const filename = `multirblx_${config.type}${info.ext}`

  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  const runInstructions: Record<ScriptType, string[]> = {
    powershell_mutex: [
      '1. Right-click the .ps1 file',
      '2. Select "Run with PowerShell"',
      '3. Click "Open" if prompted',
      '4. Keep the window open while gaming',
      '5. Press CTRL+C when done',
    ],
    handle_auto_close: [
      '1. Edit $HandleExe path in the script',
      '2. Right-click → Run with PowerShell',
      '3. Accept the UAC elevation prompt',
      '4. Keep window open while gaming',
    ],
    batch_launcher: [
      '1. Right-click the .bat file',
      '2. Select "Run as Administrator"',
      '3. Follow the on-screen instructions',
      '4. Browser will open automatically',
    ],
    startup_task: [
      '1. Right-click → Run with PowerShell',
      '2. Accept Administrator elevation',
      '3. Run ONCE to install the task',
      '4. Mutex auto-starts on every login',
      '5. To uninstall: run with -Remove',
    ],
    ahk_process_explorer: [
      '1. Install AutoHotkey v1.x (autohotkey.com)',
      '2. Download & run Process Explorer as Admin',
      '3. Enable View > Lower Pane > Handles',
      '4. Double-click the .ahk script',
      '5. Press Win+F2 after Roblox is in-game',
    ],
    windows_sandbox_config: [
      '1. Enable Windows Sandbox first (see Methods)',
      '2. Save this file as RobloxSandbox.wsb',
      '3. Double-click to launch the sandbox',
      '4. Inside sandbox: go to roblox.com',
      '5. Install Roblox, log in with alt account',
    ],
    runas_launcher: [
      '1. Create a Windows user account first',
      '2. Edit ALT_USERNAME in the script',
      '3. Double-click the .bat file',
      '4. Enter the Windows user password',
      '5. Log into alt Roblox account in new window',
    ],
  }

  return (
    <div className="min-h-screen pt-24 pb-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-10">
          <div className="font-mono text-xs text-muted-foreground uppercase tracking-widest mb-2">Tool</div>
          <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-3">
            Script <span className="gradient-text">Generator</span>
          </h1>
          <p className="text-muted-foreground text-base leading-relaxed max-w-2xl">
            7 ready-to-run scripts for every multi-instance method. Copy or download — fully annotated, no editing required (except where noted).
          </p>
        </div>

        {/* Safety notice */}
        <div className="flex items-start gap-3 p-4 rounded-xl border border-[hsl(150,100%,45%)/0.2] bg-[hsl(150,100%,45%)/0.04] mb-8">
          <Shield className="w-4 h-4 text-[hsl(150,100%,45%)] flex-shrink-0 mt-0.5" />
          <p className="text-sm text-muted-foreground">
            <span className="text-[hsl(150,100%,45%)] font-semibold">All scripts on this page are safe. </span>
            Every script is open, readable code — no compiled binaries, no obfuscation. Uses only built-in Windows APIs or official Microsoft tools. Always verify scripts you download from the internet with a text editor before running.
          </p>
        </div>

        <div className="grid lg:grid-cols-5 gap-6">
          {/* Config panel */}
          <div className="lg:col-span-2 space-y-4">

            {/* Script type selector */}
            <div className="card-dark rounded-xl p-5">
              <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
                Select Script Type
              </h3>
              <div className="space-y-2">
                {(Object.entries(SCRIPT_INFO) as [ScriptType, typeof SCRIPT_INFO[ScriptType]][]).map(([key, val]) => (
                  <button
                    key={key}
                    onClick={() => setConfig(c => ({ ...c, type: key }))}
                    className={`w-full text-left p-3 rounded-lg border transition-all ${
                      config.type === key
                        ? 'border-[hsl(180,100%,50%)/0.4] bg-[hsl(180,100%,50%)/0.07]'
                        : 'border-border hover:border-[hsl(180,100%,50%)/0.2] hover:bg-secondary'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <span className={`font-semibold text-sm leading-snug ${config.type === key ? 'text-[hsl(180,100%,50%)]' : 'text-foreground'}`}>
                        {val.title}
                      </span>
                      <StatusBadge
                        label={val.difficulty}
                        variant={val.difficulty === 'Beginner' ? 'beginner' : val.difficulty === 'Intermediate' ? 'intermediate' : 'advanced'}
                      />
                    </div>
                    <p className="text-xs text-muted-foreground leading-snug">{val.desc}</p>
                    <div className="mt-1.5 flex items-center gap-1.5">
                      <span className="font-mono text-[10px] text-muted-foreground">{val.ext}</span>
                      <StatusBadge label={val.safety} variant={val.safety === 'Safe' ? 'safe' : 'caution'} />
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Options per script type */}
            {config.type === 'powershell_mutex' && (
              <div className="card-dark rounded-xl p-5 space-y-4">
                <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider">Options</h3>

                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-sm font-medium text-foreground">Windows Notification</div>
                    <div className="text-xs text-muted-foreground">Pop-up when mutex activates</div>
                  </div>
                  <div
                    role="button"
                    tabIndex={0}
                    onClick={() => setConfig(c => ({ ...c, showNotification: !c.showNotification }))}
                    onKeyDown={e => e.key === 'Enter' && setConfig(c => ({ ...c, showNotification: !c.showNotification }))}
                    className={`w-10 h-5 rounded-full transition-all relative cursor-pointer ${config.showNotification ? 'bg-[hsl(180,100%,45%)]' : 'bg-secondary border border-border'}`}
                  >
                    <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all ${config.showNotification ? 'left-5' : 'left-0.5'}`} />
                  </div>
                </div>

                <div>
                  <div className="text-sm font-medium text-foreground mb-1">Mutex variants: {config.mutexCount}</div>
                  <div className="text-xs text-muted-foreground mb-2">More variants = more compatibility</div>
                  <input
                    type="range"
                    min={1}
                    max={2}
                    value={config.mutexCount}
                    onChange={e => setConfig(c => ({ ...c, mutexCount: Number(e.target.value) }))}
                    className="w-full accent-[hsl(180,100%,50%)]"
                  />
                  <div className="flex justify-between text-xs text-muted-foreground font-mono mt-1">
                    <span>1 = standard</span>
                    <span>2 = + Global namespace</span>
                  </div>
                </div>
              </div>
            )}

            {config.type === 'handle_auto_close' && (
              <div className="card-dark rounded-xl p-5 space-y-3">
                <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider">handle.exe Path</h3>
                <div>
                  <label className="block text-xs text-muted-foreground font-mono mb-1.5">Path to handle.exe:</label>
                  <input
                    type="text"
                    value={config.handlePath}
                    onChange={e => setConfig(c => ({ ...c, handlePath: e.target.value }))}
                    className="w-full px-3 py-2 rounded-lg bg-secondary border border-border text-xs font-mono text-foreground focus:outline-none focus:border-[hsl(180,100%,50%)/0.5] transition-colors"
                    placeholder="C:\Tools\Handle\handle.exe"
                  />
                </div>
                <div className="flex items-start gap-2 p-2.5 rounded bg-[hsl(38,92%,60%)/0.08] border border-[hsl(38,92%,60%)/0.2]">
                  <AlertTriangle className="w-3.5 h-3.5 text-[hsl(38,92%,60%)] flex-shrink-0 mt-0.5" />
                  <p className="text-xs text-[hsl(38,92%,60%)]">Download Handle.zip from Microsoft first: download.sysinternals.com/files/Handle.zip</p>
                </div>
              </div>
            )}

            {config.type === 'runas_launcher' && (
              <div className="card-dark rounded-xl p-5 space-y-3">
                <h3 className="font-mono text-xs font-semibold text-muted-foreground uppercase tracking-wider">Alt Windows User</h3>
                <div>
                  <label className="block text-xs text-muted-foreground font-mono mb-1.5">Windows username:</label>
                  <input
                    type="text"
                    value={config.altUser}
                    onChange={e => setConfig(c => ({ ...c, altUser: e.target.value }))}
                    className="w-full px-3 py-2 rounded-lg bg-secondary border border-border text-xs font-mono text-foreground focus:outline-none focus:border-[hsl(180,100%,50%)/0.5] transition-colors"
                    placeholder="RobloxAlt1"
                  />
                </div>
                <p className="text-xs text-muted-foreground">Create user first: Settings → Accounts → Family & other users → Add someone</p>
              </div>
            )}

            {/* Download button */}
            <div className="flex gap-3">
              <button
                onClick={handleDownload}
                className="btn-primary flex-1 px-4 py-3 rounded-lg flex items-center justify-center gap-2 text-sm font-semibold"
              >
                <Download className="w-4 h-4" />
                Download {info.ext}
              </button>
              <button
                onClick={() => setConfig(c => ({ ...c }))}
                className="px-3 py-3 rounded-lg border border-border text-muted-foreground hover:text-foreground hover:border-[hsl(180,100%,50%)/0.3] transition-all"
                title="Regenerate"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            </div>

            {/* Run instructions */}
            <div className="p-4 rounded-lg bg-[hsl(180,100%,50%)/0.05] border border-[hsl(180,100%,50%)/0.15] text-xs font-mono text-muted-foreground space-y-1.5">
              <div className="text-[hsl(180,100%,50%)] font-semibold mb-2 flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5" />
                Run Instructions
              </div>
              {runInstructions[config.type].map((line, i) => (
                <p key={i}>{line}</p>
              ))}
            </div>
          </div>

          {/* Code preview */}
          <div className="lg:col-span-3">
            <div className="sticky top-24">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-[hsl(180,100%,50%)]" />
                  <span className="font-mono text-sm font-semibold text-foreground">{info.title}</span>
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge label={info.ext} variant="info" />
                  <span className="font-mono text-xs text-muted-foreground">{filename}</span>
                </div>
              </div>
              <CodeBlock
                code={script}
                label={filename}
                language={info.ext.replace('.', '')}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
